export class Contatti {
	contId?: number;
	contTitolo: string;
	contNome: string;
	contCognome: string;
	contAzId?: number;
	contPosizione: string;
	contCitta: string;
	contEmail1: string;
	contEmail2: string;
	contTelefono1: string;
	contTelefono2: string;
	contRifUteId: string;
	contNote: string;
	contInsTimestamp: Date;
	contInsUteId: string;
	contModTimestamp: string;
	contModUteId: string;
	contCvIniziali: string;
	contTipoContatto: string;
	contAttivo: string;
	contDescrizione: string;
	contPriormin: number;
	contPriormax: number;
	contOrari1Giorno: string;
	contOrari1Inizio: string;
	contOrari1Fine: string;
	contOrari2Giorno: string;
	contOrari2Inizio: string;
	contOrari2Fine: string;
	contOrari3Giorno: string;
	contOrari3Inizio: string;
	contOrari3Fine: string;
	contOrari4Giorno: string;
	contOrari4Inizio: string;
	contOrari4Fine: string;
	contOrari5Giorno: string;
	contOrari5Inizio: string;
	contOrari5Fine: string;
	contInvioCvNote: string;
	contCliId: string;
	contAzsedeId?: number;

	// External table column
	azRagSociale: string;
	azsedeDescr: string;
	uteNome: string;

	constructor() {
		this.contTitolo = null;
		this.contNome = null;
		this.contCognome = null;
		this.contAzId = null;
		this.contPosizione = null;
		this.contCitta = null;
		this.contEmail1 = null;
		this.contEmail2 = null;
		this.contTelefono1 = null;
		this.contTelefono2 = null;
		this.contRifUteId = null;
		this.contNote = null;
		this.contInsTimestamp = null;
		this.contInsUteId = null;
		this.contModTimestamp = null;
		this.contModUteId = null;
		this.contCvIniziali = null;
		this.contTipoContatto = null;
		this.contAttivo = null;
		this.contDescrizione = null;
		this.contPriormin = 0;
		this.contPriormax = 0;
		this.contOrari1Giorno = null;
		this.contOrari1Inizio = null;
		this.contOrari1Fine = null;
		this.contOrari2Giorno = null;
		this.contOrari2Inizio = null;
		this.contOrari2Fine = null;
		this.contOrari3Giorno = null;
		this.contOrari3Inizio = null;
		this.contOrari3Fine = null;
		this.contOrari4Giorno = null;
		this.contOrari4Inizio = null;
		this.contOrari4Fine = null;
		this.contOrari5Giorno = null;
		this.contOrari5Inizio = null;
		this.contOrari5Fine = null;
		this.contInvioCvNote = null;
		this.contCliId = null;
	}
}