//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftSkill
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://www.wsplay.laborplay.com", ItemName="int")]
    public class ArrayOfInt : System.Collections.Generic.List<int>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseData", Namespace="http://www.wsplay.laborplay.com")]
    public partial class ResponseData : object
    {
        
        private string ErrorMessagePropField;
        
        private int ProfileIDPropField;
        
        private double PField;
        
        private double LField;
        
        private double AField;
        
        private double YField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ErrorMessageProp
        {
            get
            {
                return this.ErrorMessagePropField;
            }
            set
            {
                this.ErrorMessagePropField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ProfileIDProp
        {
            get
            {
                return this.ProfileIDPropField;
            }
            set
            {
                this.ProfileIDPropField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public double P
        {
            get
            {
                return this.PField;
            }
            set
            {
                this.PField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public double L
        {
            get
            {
                return this.LField;
            }
            set
            {
                this.LField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public double A
        {
            get
            {
                return this.AField;
            }
            set
            {
                this.AField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public double Y
        {
            get
            {
                return this.YField;
            }
            set
            {
                this.YField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfDateTime", Namespace="http://www.wsplay.laborplay.com", ItemName="dateTime")]
    public class ArrayOfDateTime : System.Collections.Generic.List<System.DateTime>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfDouble", Namespace="http://www.wsplay.laborplay.com", ItemName="double")]
    public class ArrayOfDouble : System.Collections.Generic.List<double>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt1", Namespace="http://www.wsplay.laborplay.com", ItemName="int")]
    public class ArrayOfInt1 : System.Collections.Generic.List<System.Nullable<int>>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseDataFull", Namespace="http://www.wsplay.laborplay.com")]
    public partial class ResponseDataFull : object
    {
        
        private string ErrorMessagePropField;
        
        private int ProfileIDPropField;
        
        private int ProfileID1PropField;
        
        private int ProfileID2PropField;
        
        private double PField;
        
        private double LField;
        
        private double AField;
        
        private double YField;
        
        private double P1Field;
        
        private double L1Field;
        
        private double A1Field;
        
        private double Y1Field;
        
        private double P2Field;
        
        private double L2Field;
        
        private double A2Field;
        
        private double Y2Field;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ErrorMessageProp
        {
            get
            {
                return this.ErrorMessagePropField;
            }
            set
            {
                this.ErrorMessagePropField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ProfileIDProp
        {
            get
            {
                return this.ProfileIDPropField;
            }
            set
            {
                this.ProfileIDPropField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int ProfileID1Prop
        {
            get
            {
                return this.ProfileID1PropField;
            }
            set
            {
                this.ProfileID1PropField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int ProfileID2Prop
        {
            get
            {
                return this.ProfileID2PropField;
            }
            set
            {
                this.ProfileID2PropField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public double P
        {
            get
            {
                return this.PField;
            }
            set
            {
                this.PField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public double L
        {
            get
            {
                return this.LField;
            }
            set
            {
                this.LField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public double A
        {
            get
            {
                return this.AField;
            }
            set
            {
                this.AField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public double Y
        {
            get
            {
                return this.YField;
            }
            set
            {
                this.YField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public double P1
        {
            get
            {
                return this.P1Field;
            }
            set
            {
                this.P1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public double L1
        {
            get
            {
                return this.L1Field;
            }
            set
            {
                this.L1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public double A1
        {
            get
            {
                return this.A1Field;
            }
            set
            {
                this.A1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public double Y1
        {
            get
            {
                return this.Y1Field;
            }
            set
            {
                this.Y1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public double P2
        {
            get
            {
                return this.P2Field;
            }
            set
            {
                this.P2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public double L2
        {
            get
            {
                return this.L2Field;
            }
            set
            {
                this.L2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=14)]
        public double A2
        {
            get
            {
                return this.A2Field;
            }
            set
            {
                this.A2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=15)]
        public double Y2
        {
            get
            {
                return this.Y2Field;
            }
            set
            {
                this.Y2Field = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.wsplay.laborplay.com", ConfigurationName="SoftSkill.wsTestPlayPublicSoap")]
    public interface wsTestPlayPublicSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.wsplay.laborplay.com/Message", ReplyAction="*")]
        System.Threading.Tasks.Task<SoftSkill.MessageResponse> MessageAsync(SoftSkill.MessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action= "http://wsplay.laborplay.com/wsTestPlayPublic.asmx?op=GetSkillsProfile", ReplyAction="*")]
        System.Threading.Tasks.Task<SoftSkill.GetSkillsProfileResponse> GetSkillsProfileAsync(SoftSkill.GetSkillsProfileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.wsplay.laborplay.com/GetProfileScore", ReplyAction="*")]
        System.Threading.Tasks.Task<SoftSkill.GetProfileScoreResponse> GetProfileScoreAsync(SoftSkill.GetProfileScoreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.wsplay.laborplay.com/GetProfileFull", ReplyAction="*")]
        System.Threading.Tasks.Task<SoftSkill.GetProfileFullResponse> GetProfileFullAsync(SoftSkill.GetProfileFullRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.wsplay.laborplay.com/GetProfile", ReplyAction="*")]
        System.Threading.Tasks.Task<SoftSkill.GetProfileResponse> GetProfileAsync(SoftSkill.GetProfileRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MessageRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Message", Namespace="http://www.wsplay.laborplay.com", Order=0)]
        public SoftSkill.MessageRequestBody Body;
        
        public MessageRequest()
        {
        }
        
        public MessageRequest(SoftSkill.MessageRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class MessageRequestBody
    {
        
        public MessageRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MessageResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MessageResponse", Namespace="http://www.wsplay.laborplay.com", Order=0)]
        public SoftSkill.MessageResponseBody Body;
        
        public MessageResponse()
        {
        }
        
        public MessageResponse(SoftSkill.MessageResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.wsplay.laborplay.com")]
    public partial class MessageResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string MessageResult;
        
        public MessageResponseBody()
        {
        }
        
        public MessageResponseBody(string MessageResult)
        {
            this.MessageResult = MessageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSkillsProfileRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSkillsProfile", Namespace="http://www.wsplay.laborplay.com", Order=0)]
        public SoftSkill.GetSkillsProfileRequestBody Body;
        
        public GetSkillsProfileRequest()
        {
        }
        
        public GetSkillsProfileRequest(SoftSkill.GetSkillsProfileRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.wsplay.laborplay.com")]
    public partial class GetSkillsProfileRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SoftSkill.ArrayOfInt SkillsList;
        
        public GetSkillsProfileRequestBody()
        {
        }
        
        public GetSkillsProfileRequestBody(SoftSkill.ArrayOfInt SkillsList)
        {
            this.SkillsList = SkillsList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSkillsProfileResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSkillsProfileResponse", Namespace="http://www.wsplay.laborplay.com", Order=0)]
        public SoftSkill.GetSkillsProfileResponseBody Body;
        
        public GetSkillsProfileResponse()
        {
        }
        
        public GetSkillsProfileResponse(SoftSkill.GetSkillsProfileResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.wsplay.laborplay.com")]
    public partial class GetSkillsProfileResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SoftSkill.ResponseData GetSkillsProfileResult;
        
        public GetSkillsProfileResponseBody()
        {
        }
        
        public GetSkillsProfileResponseBody(SoftSkill.ResponseData GetSkillsProfileResult)
        {
            this.GetSkillsProfileResult = GetSkillsProfileResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProfileScoreRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProfileScore", Namespace="http://www.wsplay.laborplay.com", Order=0)]
        public SoftSkill.GetProfileScoreRequestBody Body;
        
        public GetProfileScoreRequest()
        {
        }
        
        public GetProfileScoreRequest(SoftSkill.GetProfileScoreRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.wsplay.laborplay.com")]
    public partial class GetProfileScoreRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double BestScore;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime BestSCoreDatetime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public SoftSkill.ArrayOfDateTime LastScoresDateTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public SoftSkill.ArrayOfDouble LastScores;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public double PlayerPlayP;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public double PlayerPlayL;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public double PlayerPlayA;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public double PlayerPlayY;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public double GamePlayP;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public double GamePlayL;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public double GamePlayA;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public double GamePlayY;
        
        public GetProfileScoreRequestBody()
        {
        }
        
        public GetProfileScoreRequestBody(double BestScore, System.DateTime BestSCoreDatetime, SoftSkill.ArrayOfDateTime LastScoresDateTime, SoftSkill.ArrayOfDouble LastScores, double PlayerPlayP, double PlayerPlayL, double PlayerPlayA, double PlayerPlayY, double GamePlayP, double GamePlayL, double GamePlayA, double GamePlayY)
        {
            this.BestScore = BestScore;
            this.BestSCoreDatetime = BestSCoreDatetime;
            this.LastScoresDateTime = LastScoresDateTime;
            this.LastScores = LastScores;
            this.PlayerPlayP = PlayerPlayP;
            this.PlayerPlayL = PlayerPlayL;
            this.PlayerPlayA = PlayerPlayA;
            this.PlayerPlayY = PlayerPlayY;
            this.GamePlayP = GamePlayP;
            this.GamePlayL = GamePlayL;
            this.GamePlayA = GamePlayA;
            this.GamePlayY = GamePlayY;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProfileScoreResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProfileScoreResponse", Namespace="http://www.wsplay.laborplay.com", Order=0)]
        public SoftSkill.GetProfileScoreResponseBody Body;
        
        public GetProfileScoreResponse()
        {
        }
        
        public GetProfileScoreResponse(SoftSkill.GetProfileScoreResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.wsplay.laborplay.com")]
    public partial class GetProfileScoreResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SoftSkill.ResponseData GetProfileScoreResult;
        
        public GetProfileScoreResponseBody()
        {
        }
        
        public GetProfileScoreResponseBody(SoftSkill.ResponseData GetProfileScoreResult)
        {
            this.GetProfileScoreResult = GetProfileScoreResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProfileFullRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProfileFull", Namespace="http://www.wsplay.laborplay.com", Order=0)]
        public SoftSkill.GetProfileFullRequestBody Body;
        
        public GetProfileFullRequest()
        {
        }
        
        public GetProfileFullRequest(SoftSkill.GetProfileFullRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.wsplay.laborplay.com")]
    public partial class GetProfileFullRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Genere;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int MobileFrequenzaGioco;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public bool MobileGiocoAvventura;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public bool MobileGiocoAzione;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool MobileGiocoGDR;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool MobileGiocoPuzzle;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public bool MobileGiocoSimulazione;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public bool MobileGiocoStrategia;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public SoftSkill.ArrayOfInt1 RisposteQuestionario;
        
        public GetProfileFullRequestBody()
        {
        }
        
        public GetProfileFullRequestBody(int Genere, int MobileFrequenzaGioco, bool MobileGiocoAvventura, bool MobileGiocoAzione, bool MobileGiocoGDR, bool MobileGiocoPuzzle, bool MobileGiocoSimulazione, bool MobileGiocoStrategia, SoftSkill.ArrayOfInt1 RisposteQuestionario)
        {
            this.Genere = Genere;
            this.MobileFrequenzaGioco = MobileFrequenzaGioco;
            this.MobileGiocoAvventura = MobileGiocoAvventura;
            this.MobileGiocoAzione = MobileGiocoAzione;
            this.MobileGiocoGDR = MobileGiocoGDR;
            this.MobileGiocoPuzzle = MobileGiocoPuzzle;
            this.MobileGiocoSimulazione = MobileGiocoSimulazione;
            this.MobileGiocoStrategia = MobileGiocoStrategia;
            this.RisposteQuestionario = RisposteQuestionario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProfileFullResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProfileFullResponse", Namespace="http://www.wsplay.laborplay.com", Order=0)]
        public SoftSkill.GetProfileFullResponseBody Body;
        
        public GetProfileFullResponse()
        {
        }
        
        public GetProfileFullResponse(SoftSkill.GetProfileFullResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.wsplay.laborplay.com")]
    public partial class GetProfileFullResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SoftSkill.ResponseDataFull GetProfileFullResult;
        
        public GetProfileFullResponseBody()
        {
        }
        
        public GetProfileFullResponseBody(SoftSkill.ResponseDataFull GetProfileFullResult)
        {
            this.GetProfileFullResult = GetProfileFullResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProfileRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProfile", Namespace="http://www.wsplay.laborplay.com", Order=0)]
        public SoftSkill.GetProfileRequestBody Body;
        
        public GetProfileRequest()
        {
        }
        
        public GetProfileRequest(SoftSkill.GetProfileRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.wsplay.laborplay.com")]
    public partial class GetProfileRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Genere;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int MobileFrequenzaGioco;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public bool MobileGiocoAvventura;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public bool MobileGiocoAzione;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool MobileGiocoGDR;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool MobileGiocoPuzzle;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public bool MobileGiocoSimulazione;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public bool MobileGiocoStrategia;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public SoftSkill.ArrayOfInt1 RisposteQuestionario;
        
        public GetProfileRequestBody()
        {
        }
        
        public GetProfileRequestBody(int Genere, int MobileFrequenzaGioco, bool MobileGiocoAvventura, bool MobileGiocoAzione, bool MobileGiocoGDR, bool MobileGiocoPuzzle, bool MobileGiocoSimulazione, bool MobileGiocoStrategia, SoftSkill.ArrayOfInt1 RisposteQuestionario)
        {
            this.Genere = Genere;
            this.MobileFrequenzaGioco = MobileFrequenzaGioco;
            this.MobileGiocoAvventura = MobileGiocoAvventura;
            this.MobileGiocoAzione = MobileGiocoAzione;
            this.MobileGiocoGDR = MobileGiocoGDR;
            this.MobileGiocoPuzzle = MobileGiocoPuzzle;
            this.MobileGiocoSimulazione = MobileGiocoSimulazione;
            this.MobileGiocoStrategia = MobileGiocoStrategia;
            this.RisposteQuestionario = RisposteQuestionario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetProfileResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetProfileResponse", Namespace="http://www.wsplay.laborplay.com", Order=0)]
        public SoftSkill.GetProfileResponseBody Body;
        
        public GetProfileResponse()
        {
        }
        
        public GetProfileResponse(SoftSkill.GetProfileResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.wsplay.laborplay.com")]
    public partial class GetProfileResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public SoftSkill.ResponseData GetProfileResult;
        
        public GetProfileResponseBody()
        {
        }
        
        public GetProfileResponseBody(SoftSkill.ResponseData GetProfileResult)
        {
            this.GetProfileResult = GetProfileResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface wsTestPlayPublicSoapChannel : SoftSkill.wsTestPlayPublicSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class wsTestPlayPublicSoapClient : System.ServiceModel.ClientBase<SoftSkill.wsTestPlayPublicSoap>, SoftSkill.wsTestPlayPublicSoap
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public wsTestPlayPublicSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(wsTestPlayPublicSoapClient.GetBindingForEndpoint(endpointConfiguration), wsTestPlayPublicSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsTestPlayPublicSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(wsTestPlayPublicSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsTestPlayPublicSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(wsTestPlayPublicSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public wsTestPlayPublicSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftSkill.MessageResponse> SoftSkill.wsTestPlayPublicSoap.MessageAsync(SoftSkill.MessageRequest request)
        {
            return base.Channel.MessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftSkill.MessageResponse> MessageAsync()
        {
            SoftSkill.MessageRequest inValue = new SoftSkill.MessageRequest();
            inValue.Body = new SoftSkill.MessageRequestBody();
            return ((SoftSkill.wsTestPlayPublicSoap)(this)).MessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftSkill.GetSkillsProfileResponse> SoftSkill.wsTestPlayPublicSoap.GetSkillsProfileAsync(SoftSkill.GetSkillsProfileRequest request)
        {
            return base.Channel.GetSkillsProfileAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftSkill.GetSkillsProfileResponse> GetSkillsProfileAsync(SoftSkill.ArrayOfInt SkillsList)
        {
            SoftSkill.GetSkillsProfileRequest inValue = new SoftSkill.GetSkillsProfileRequest();
            inValue.Body = new SoftSkill.GetSkillsProfileRequestBody();
            inValue.Body.SkillsList = SkillsList;
         
            return ((SoftSkill.wsTestPlayPublicSoap)(this)).GetSkillsProfileAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftSkill.GetProfileScoreResponse> SoftSkill.wsTestPlayPublicSoap.GetProfileScoreAsync(SoftSkill.GetProfileScoreRequest request)
        {
            return base.Channel.GetProfileScoreAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftSkill.GetProfileScoreResponse> GetProfileScoreAsync(double BestScore, System.DateTime BestSCoreDatetime, SoftSkill.ArrayOfDateTime LastScoresDateTime, SoftSkill.ArrayOfDouble LastScores, double PlayerPlayP, double PlayerPlayL, double PlayerPlayA, double PlayerPlayY, double GamePlayP, double GamePlayL, double GamePlayA, double GamePlayY)
        {
            SoftSkill.GetProfileScoreRequest inValue = new SoftSkill.GetProfileScoreRequest();
            inValue.Body = new SoftSkill.GetProfileScoreRequestBody();
            inValue.Body.BestScore = BestScore;
            inValue.Body.BestSCoreDatetime = BestSCoreDatetime;
            inValue.Body.LastScoresDateTime = LastScoresDateTime;
            inValue.Body.LastScores = LastScores;
            inValue.Body.PlayerPlayP = PlayerPlayP;
            inValue.Body.PlayerPlayL = PlayerPlayL;
            inValue.Body.PlayerPlayA = PlayerPlayA;
            inValue.Body.PlayerPlayY = PlayerPlayY;
            inValue.Body.GamePlayP = GamePlayP;
            inValue.Body.GamePlayL = GamePlayL;
            inValue.Body.GamePlayA = GamePlayA;
            inValue.Body.GamePlayY = GamePlayY;
            return ((SoftSkill.wsTestPlayPublicSoap)(this)).GetProfileScoreAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftSkill.GetProfileFullResponse> SoftSkill.wsTestPlayPublicSoap.GetProfileFullAsync(SoftSkill.GetProfileFullRequest request)
        {
            return base.Channel.GetProfileFullAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftSkill.GetProfileFullResponse> GetProfileFullAsync(int Genere, int MobileFrequenzaGioco, bool MobileGiocoAvventura, bool MobileGiocoAzione, bool MobileGiocoGDR, bool MobileGiocoPuzzle, bool MobileGiocoSimulazione, bool MobileGiocoStrategia, SoftSkill.ArrayOfInt1 RisposteQuestionario)
        {
            SoftSkill.GetProfileFullRequest inValue = new SoftSkill.GetProfileFullRequest();
            inValue.Body = new SoftSkill.GetProfileFullRequestBody();
            inValue.Body.Genere = Genere;
            inValue.Body.MobileFrequenzaGioco = MobileFrequenzaGioco;
            inValue.Body.MobileGiocoAvventura = MobileGiocoAvventura;
            inValue.Body.MobileGiocoAzione = MobileGiocoAzione;
            inValue.Body.MobileGiocoGDR = MobileGiocoGDR;
            inValue.Body.MobileGiocoPuzzle = MobileGiocoPuzzle;
            inValue.Body.MobileGiocoSimulazione = MobileGiocoSimulazione;
            inValue.Body.MobileGiocoStrategia = MobileGiocoStrategia;
            inValue.Body.RisposteQuestionario = RisposteQuestionario;
            return ((SoftSkill.wsTestPlayPublicSoap)(this)).GetProfileFullAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftSkill.GetProfileResponse> SoftSkill.wsTestPlayPublicSoap.GetProfileAsync(SoftSkill.GetProfileRequest request)
        {
            return base.Channel.GetProfileAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftSkill.GetProfileResponse> GetProfileAsync(int Genere, int MobileFrequenzaGioco, bool MobileGiocoAvventura, bool MobileGiocoAzione, bool MobileGiocoGDR, bool MobileGiocoPuzzle, bool MobileGiocoSimulazione, bool MobileGiocoStrategia, SoftSkill.ArrayOfInt1 RisposteQuestionario)
        {
            SoftSkill.GetProfileRequest inValue = new SoftSkill.GetProfileRequest();
            inValue.Body = new SoftSkill.GetProfileRequestBody();
            inValue.Body.Genere = Genere;
            inValue.Body.MobileFrequenzaGioco = MobileFrequenzaGioco;
            inValue.Body.MobileGiocoAvventura = MobileGiocoAvventura;
            inValue.Body.MobileGiocoAzione = MobileGiocoAzione;
            inValue.Body.MobileGiocoGDR = MobileGiocoGDR;
            inValue.Body.MobileGiocoPuzzle = MobileGiocoPuzzle;
            inValue.Body.MobileGiocoSimulazione = MobileGiocoSimulazione;
            inValue.Body.MobileGiocoStrategia = MobileGiocoStrategia;
            inValue.Body.RisposteQuestionario = RisposteQuestionario;
            return ((SoftSkill.wsTestPlayPublicSoap)(this)).GetProfileAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.wsTestPlayPublicSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.wsTestPlayPublicSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.wsTestPlayPublicSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://wsplay.laborplay.com/wsTestPlayPublic.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.wsTestPlayPublicSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://wsplay.laborplay.com/wsTestPlayPublic.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            wsTestPlayPublicSoap,
            
            wsTestPlayPublicSoap12,
        }
    }
}
